# Generated by Django 2.2.7 on 2019-12-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(blank=True, verbose_name='年龄')),
                ('sex', models.IntegerField(choices=[('1', '男'), ('0', '女')], default=1, verbose_name='性别')),
            ],
        ),
    ]
