# Generated by Django 2.2.7 on 2019-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0005_auto_20191218_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
